language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=4.5 WP_MULTISITE=0

matrix:
  include:
    - php: 5.3
      env: WP_VERSION=latest WP_MULTISITE=1

before_script:
  - git clone https://github.com/woothemes/woocommerce ../woocommerce
  - bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit
